package rules

import com.ftn.sbnz.model.models.Finding
import com.ftn.sbnz.service.services.FindingsService

global FindingsService findingsService

// PERSISTENCE ACTIONS
agenda-group "persist.actions"

rule "Persist findings to global store"
when
    // match only findings that have NOT been notified/persisted yet
    $finding : Finding( notified == false, $moduleId : moduleId )
then
    // mark as notified so subsequent rules in the same session don't repersist
    $finding.setNotified(true);
    update($finding);
    // persist to global store
    findingsService.addFindings($moduleId, java.util.Arrays.asList($finding));
end
